version: "3.9"

services:

  backend:
    build: ./backend
    container_name: wind-backend
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: wind-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend